完善细节，补充了一些自己的总结
southernEast/SEU_553 pull request #4
Opened 2023-04-05 03:34 UTC by TheCoderAlex

修改了:

- 未增加的头文件
- 不同解法

增加了:
+ 排序算法的总结
+ Map哈希表的总结

2023-04-05 13:04 UTC, southernEast requested changes
同学你好，欢迎一起建设这个项目！其中部分代码有一些需要调整，我已经添加review了，麻烦同学重新看一下，谢谢！

2023-04-05 13:04 UTC, southernEast commented on 2012/2/2.cpp
> +    }
这个大括号“}”的缩进似乎不太对齐。

2023-04-05 13:04 UTC, southernEast commented on 2013/1/1.cpp
> +void prime(int n) {
请将函数接口改为一致接口。

2023-04-05 13:04 UTC, southernEast commented on 2013/1/1.cpp
> +            for (int j = i * i; j <= n; j+=i)
> j = i * i;

似乎有部分数字会被跳过？

2023-04-05 13:04 UTC, southernEast commented on 2013/1/1.cpp
> +
请将代码的缩进与文件内容保持一致。

2023-04-05 13:04 UTC, southernEast commented on 2013/1/1.cpp
> +    for (int i = 2; i * i <= n; ++i) {
> i * i <= n;

每次循环都会多算一次乘法，如果要完全发挥改进的埃式筛法的优点的话，是不是将这个sqrt值用一个临时变量保存一下时间效率会更高？

2023-04-05 13:04 UTC, southernEast commented on 2015/4/4.cpp
> +}
请将代码的缩进与原始文件内容保持一致。

2023-04-05 13:04 UTC, southernEast commented on 部分其他题目总结/排序算法.cpp
> +{
请将这个文件括号的换行与之前文件格式保持一致。

2023-04-05 13:04 UTC, southernEast commented on 常用函数总结/map哈希表.cpp
> +   cout<<"Do not Find"<<endl;
这里的缩进与18行似乎不一样。

2023-04-05 13:04 UTC, southernEast commented on 常用函数总结/map哈希表.cpp
> +    return a.second < b.second;
缩进似乎不一样？

2023-04-05 14:29 UTC, TheCoderAlex commented on 2013/1/1.cpp
> +            for (int j = i * i; j <= n; j+=i)
因为从 2 到 i - 1 的倍数在之前被筛过了，因此不会漏筛。但是此时只能通过is_prime数组找素数，不能像之前的算法一样将素数全都塞到vector中，这样确实会漏数字。

2023-04-05 14:31 UTC, ZephyrFT commented on 2012/2/2.cpp
> +    }
已对齐

2023-04-05 14:39 UTC, TheCoderAlex commented on 2013/1/1.cpp
> +            for (int j = i * i; j <= n; j+=i)
因为从 2 到 i - 1 的倍数之前筛过了，这里直接从 i的倍数开始，不会漏筛

2023-04-05 14:41 UTC, TheCoderAlex commented on 2013/1/1.cpp
> +    for (int i = 2; i * i <= n; ++i) {
可以，已修改

2023-04-05 15:09 UTC, southernEast commented on 2013/1/1.cpp
> +            for (int j = i * i; j <= n; j+=i)
噢！是的，这里没有问题，抱歉，欠考虑了。

2023-04-05 15:16 UTC, ZephyrFT commented on 部分其他题目总结/排序算法.cpp
> +{
已修改

2023-04-05 15:16 UTC, ZephyrFT commented on 常用函数总结/map哈希表.cpp
> +    return a.second < b.second;
已修改

2023-04-05 15:16 UTC, ZephyrFT commented on 2015/4/4.cpp
> +}
已修改

2023-04-05 15:16 UTC, TheCoderAlex commented on 2013/1/1.cpp
> +
已修改

2023-04-05 15:16 UTC, TheCoderAlex commented on 2013/1/1.cpp
> +void prime(int n) {
已修改

2023-04-07 10:53 UTC, TheCoderAlex commented
抱歉，这两天电脑 出了点问题，我直接在github上修改好了，你看看还有什么问题

2023-04-08 05:00 UTC, southernEast requested changes
同学你好，还有两处缩进没有调整，请核对一下。

2023-04-08 05:00 UTC, southernEast commented on 常用函数总结/map哈希表.cpp
> +	cout << i.first << ' ' << i.second << endl;
这里与你的34行缩进不一致

2023-04-08 05:00 UTC, southernEast commented on 2015/4/4.cpp
> +}
这个函数的代码缩进与解法一和解法二的缩进还是有所不同。

2023-04-08 08:09 UTC, TheCoderAlex commented on 2015/4/4.cpp
> +}
我重新commit了一下，请看下这样是否可以

2023-04-09 07:55 UTC, southernEast approved these changes
感谢分享！

2023-04-09 07:55 UTC, southernEast commented on 2015/4/4.cpp
> +}
还是有一点点不一致，我给你合入了。

2023-04-09 07:57 UTC, merged